### ISSUE TITLE
MessageBodyProviderNotFoundException for com.spotify.docker.client.messages.Version when using Docker 1.10.3

### ISSUE THREAD

**Issue by wemu** [spotify/docker-maven-plugin#271] opened 2016-08-29 14:19 UTC
## Description

When using Docker 1.10.3 we get an exception when executing docker:build:

`org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
`
## How to reproduce

create a very basic docker image (we use develar/java:latest as base image and only add a spring boot jar)

## What do you expect

As with the older (1.9 ?) version of docker we expected an image to be created.

## What happened instead

Exception is thrown (see below). Build fails.

## Software:

- docker version: 
Client:
  Version:         1.10.3
  API version:     1.22
  Package version: docker-common-1.10.3-46.el7.10.x86_64
  Go version:      go1.6.2
  Git commit:      2a93377-unsupported
  Built:           Fri Jul 29 13:45:25 2016
  OS/Arch:         linux/amd64
 
 Server:
  Version:         1.10.3
  API version:     1.22
  Package version: docker-common-1.10.3-46.el7.10.x86_64
  Go version:      go1.6.2
  Git commit:      2a93377-unsupported
  Built:           Fri Jul 29 13:45:25 2016
  OS/Arch:         linux/amd64

- docker-maven-plugin version: 0.4.12
- maven version: 3.3.9 and 3.2.3

## Full backtrace

```text
[15:56:13]W:	 [Step 9/10] [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.12:build (default-cli) on project mobitor: Exception caught: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version. -> [Help 1]
[15:56:13] :	 [Step 9/10] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.12:build (default-cli) on project mobitor: Exception caught
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
[15:56:13] :	 [Step 9/10] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:56:13] :	 [Step 9/10] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:56:13] :	 [Step 9/10] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:56:13] :	 [Step 9/10] 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:56:13] :	 [Step 9/10] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[15:56:13] :	 [Step 9/10] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[15:56:13] :	 [Step 9/10] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[15:56:13] :	 [Step 9/10] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[15:56:13] :	 [Step 9/10] Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:141)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[15:56:13] :	 [Step 9/10] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[15:56:13] :	 [Step 9/10] 	... 19 more
[15:56:13] :	 [Step 9/10] Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1608)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1539)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:393)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:1647)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1148)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1107)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:567)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:351)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:139)
[15:56:13] :	 [Step 9/10] 	... 22 more
[15:56:13] :	 [Step 9/10] Caused by: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
[15:56:13] :	 [Step 9/10] 	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
[15:56:13] :	 [Step 9/10] 	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
[15:56:13] :	 [Step 9/10] 	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
[15:56:13] :	 [Step 9/10] 	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1537)
[15:56:13] :	 [Step 9/10] 	... 29 more
[15:56:13] :	 [Step 9/10] Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:232)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:785)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:790)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[15:56:13] :	 [Step 9/10] 	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
[15:56:13] :	 [Step 9/10] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:56:13] :	 [Step 9/10] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:56:13] :	 [Step 9/10] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:56:13] :	 [Step 9/10] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:56:13] :	 [Step 9/10] 	at java.lang.Thread.run(Thread.java:745)
[15:56:13]W:	 [Step 9/10] [ERROR] 
[15:56:13]W:	 [Step 9/10] [ERROR] 
[15:56:13]W:	 [Step 9/10] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[15:56:13]W:	 [Step 9/10] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[15:56:13]W:	 [Step 9/10] Process exited with code 1
```

**Comment by vberruchon** [comment] 2016-09-05 16:10
I got the same problem using the Docker-Client library and using Docker 1.10.3 engine.
I was working OK with 1.9.1 Docker engine.

**Comment by chrislovsund** [comment] 2016-09-05 18:43
Same issue on Docker `Server Version: 1.10.3`.
Work around using docker-maven-plugin 0.2.13

**Comment by mattnworb** [comment] 2016-09-07 13:15
This sounds related to https://github.com/spotify/docker-client/issues/486 which was caused by https://github.com/docker/docker/issues/25927. In other words it sounds like that version of docker accidentally introduced an API change where responses are returned as text/plain instead of json.

@vberruchon @chrislovsund is it possible to try a different version of Docker?

**Comment by chrislovsund** [comment] 2016-09-07 19:24
Yes, looks related as it doesn't work on RHEL7.

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64
```

But works on Fedora and Mac OS.
```
> cat /etc/redhat-release
Fedora release 24 (Twenty Four)

> docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-26.git1ecb834.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      1ecb834/1.10.3
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-26.git1ecb834.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      1ecb834/1.10.3
 Built:
 OS/Arch:         linux/amd64


$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
 ```

Someone mentions a patch being on the way from RedHat in spotify/docker-client#486 .

**Comment by mattnworb** [comment] 2016-09-19 13:33
I am going to close this as the issue seems to be upstream in docker 1.10 itself.

**Closed by mattnworb** 2016-09-19 13:33 UTC

**Comment by brunnels** [comment] 2016-09-29 11:44
@mattnworb I understand this is a docker problem but since it's just the content-type of the http header rather than the API output that is wrong would it be possible to change docker-maven-plugin to treat http content-type as json?  This would get those of us forced to use only official RHEL 7 packages working again.  It could take them a long time to release a new package.

Right now as a workaround I ```mvn-Pprod package docker:build -DpushImage``` to a local boot2docker vm which tags and pushes the image to a private repo.  Then I manually pull the new image into the RHEL 7 docker.
