### ISSUE TITLE
mvn clean package docker:build failing

### ISSUE THREAD

**Issue by samaddico** [spotify/docker-maven-plugin#105] opened 2015-06-29 09:14 UTC
Hi ,

So I added these to my pom.xml,to build a docker image of my project.But for some reason it fails.

    <plugin>
        <groupId>com.spotify</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.2.11</version>
     <configuration>  
           <imageName>nurs-template-engine</imageName>
           <baseImage>java</baseImage>
           <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
         <resources>
               <resource>
                        <targetPath>/</targetPath>
                        <directory>${project.build.directory}</directory>
                        <include>${project.build.finalName}.jar</include>
               </resource>
      </resources>
      </configuration>
    </plugin>

I keep having this error. i dont know what it means, i have searched through the web but to no avail.Any help will be much appreciated.

```
--- docker-maven-plugin:0.2.11:build (default-cli) @ template-engine ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Copying /home/dreamadmin/NetBeansProjects/nurs/template-engine/target/template-engine-1.0-SNAPSHOT.jar -> /home/dreamadmin/NetBeansProjects/nurs/template-engine/target/docker/template-engine-1.0-SNAPSHOT.jar
[INFO] Building image nurs-template-engine
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.777s
[INFO] Finished at: Fri Jun 26 17:36:37 WAT 2015
[INFO] Final Memory: 18M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.11:build (default-cli) on project template-engine: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Permission denied -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```
Thanks in advance

**Comment by vishal-biyani** [comment] 2015-06-30 01:07
Are you running this from jenkins or from command line?

**Comment by samaddico** [comment] 2015-06-30 05:48
From command.

**Comment by ojacquemart** [comment] 2015-07-05 20:34
I got the same error running it from a jenkins job.
Any idea of what could cause the exception?

**Comment by rohansingh** [comment] 2015-07-06 15:51
Guessing the problem is that your `DOCKER_HOST` variable is not set correctly. Does `docker ps` work for you on the same command-line?

**Comment by samaddico** [comment] 2015-07-06 15:57
No please, its not working

On 6 July 2015 at 16:51, Rohan Singh <notifications@github.com> wrote:

> Guessing the problem is that your DOCKER_HOST variable is not set
> correctly. Does docker ps work for you on the same command-line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-maven-plugin/issues/105#issuecomment-118906007>
> .
>



-- 
Samuel Anertey Addico
Software Engineer

Mobile: +2332 040 8005
skype: samuel.addico

**Comment by rohansingh** [comment] 2015-07-06 16:04
Sorry, we can't help you without details. What exactly happens when you run `docker ps` or `docker version` from the command-line? For example:

```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

**Comment by samaddico** [comment] 2015-07-06 17:41
Get http://xxx.xx.xx.x:2376/v1.19/images/json: read tcp xxx.xx.xx.xx:2376:
connection reset by peer. Are you trying to connect to a TLS-enabled daemon
without TLS?

On 6 July 2015 at 17:04, Rohan Singh <notifications@github.com> wrote:

> Sorry, we can't help you without details. What exactly happens when you
> run docker ps or docker version from the command-line? For example:
>
> $ docker version
> Client version: 1.6.0
> Client API version: 1.18
> Go version (client): go1.4.2
> Git commit (client): 4749651
> OS/Arch (client): linux/amd64
> Server version: 1.6.0
> Server API version: 1.18
> Go version (server): go1.4.2
> Git commit (server): 4749651
> OS/Arch (server): linux/amd64
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-maven-plugin/issues/105#issuecomment-118910475>
> .
>



-- 
Samuel Anertey Addico
Software Engineer

Mobile: +2332 040 8005
skype: samuel.addico

**Comment by samaddico** [comment] 2015-07-06 17:45
Response below :
```
Get http://xxx.xx.xx.x:2376/v1.19/images/json: read tcp xxx.xx.xx.xx:2376: connection reset by peer. Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by rohansingh** [comment] 2015-07-06 18:10
OK, there's some configuration issue with how you've setup Docker. Take a look at the Docker docs and ensure you have things installed and configured correctly. Until the Docker command-line works, there's no way that the Maven plugin will work.

Closing this for now since it's not an issue with docker-maven-plugin.

**Closed by rohansingh** 2015-07-06 18:10 UTC

**Comment by alexGalushka** [comment] 2015-07-23 21:40
@ samaddico I have the same exact issue with the same exact log, have you figured what was wrong in your Docker setup?

**Comment by samaddico** [comment] 2015-07-24 09:28
Hi Alex,I did a system restart and it worked.But my team members kept having this same issue,even after i commited to version control system,so i used another plugin.

**Comment by hrandika** [comment] 2015-08-02 17:09
@samaddico I had the same issue. after I ran docker without 'sudo' permission that solved.It explained here.
http://bsaunder.github.io/2014/12/21/running-docker-without-sudo/

**Comment by aksakalli** [comment] 2016-01-11 16:37
That port is owned by root so you need to run the docker task as root.

```
sudo mvn docker:build
```

Or change the user of Docker as @hrandika mentioned: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

**Comment by anick16** [comment] 2016-09-14 14:04
I too had this issue when I was running the build from Bamboo. It was due to the variable, being used for image name, was in capital letter and docker doesnt allow image names having caps

**Comment by vdua** [comment] 2017-03-08 15:33
I am getting the same error. `docker ps` and all other docker commands work fine but when running from maven it throws the same error.
```
 Failed to execute goal com.spotify:docker-maven-plugin:0.4.14-SNAPSHOT:build (default-cli) on project cli-sample: Exception caught: Request error: POST unix://localhost:80/build?t=example: 500: HTTP 500 Internal Server Error -> [Help 1]
```

The value of dockerHost is `unix:///var/run/docker.sock` but in the logs it shows as `unix://localhost:80`. I debugged and found out that  [DefaultDockerClient](https://github.com/spotify/docker-client/blob/b2e742ebf29da279b95841ac272dd7f15c8f4dfc/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L177) doesn't support this specific port.

**Comment by szgz** [comment] 2017-03-27 03:16
you can try:
    add user jenkins to docker group: usermod -G docker jenkins

reason: jenkins should run docker commond, but docker installed as root, so jenkins not have privlege to run docker

**Comment by NorrinRadd** [comment] 2017-10-04 18:56
@vdua That seems like the most valid response I've seen here.  Any progress on a fix for that?

**Comment by tormodatt** [comment] 2018-03-22 14:12
If you are running it through something like bamboo, remember to restart both docker.service and bamboo-agent.service after adding the user in the docker group. Groups changes are not loaded while its running.

**Comment by WThamira** [comment] 2018-04-18 13:31
I also had same issue.
`INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Broken pipe`

problem in here is image name : my image name is
` [INFO] Image will be built as springio/cloud-microservice-projet-Eureka:latest`

capital ‘E’  is make problem for me. If i change it to simple letter. now it work correct. 

this plugin is working correct 

```
<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<version>1.3.6</version>
				<executions>
					<execution>
						<id>default</id>
						<phase>install</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<repository>${docker.image.prefix}/${project.artifactId}</repository>
					<buildArgs>
						<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
					</buildArgs>
				</configuration>
			</plugin>
```

**Comment by serdarturkmen** [comment] 2018-05-03 12:29
add jenkins to docker group
sudo usermod -aG docker jenkins

Then restart your jenkins server to refresh the group.

**Comment by mahmoudabbasi** [comment] 2020-10-14 06:19
please check java version , so check Dockerfile and Dockerdir access 775 and check Dockerfile have a entrypoint.
