### ISSUE TITLE
serverId overrides default docker-hub repo

### ISSUE THREAD

**Issue by maven2016** [spotify/docker-maven-plugin#257] opened 2016-08-06 12:37 UTC
## Description

[Add feature/bug description here]
Bug - serverId overrides default docker-hub repo
## How to reproduce

I'm using Dockerfile:
FROM java:8

pom.xml has <serverId> configured which points to maven-settings-xml with the private repo details.
## What do you expect

i'd expect the Dockerfile be able to pull the image from the default public repo instead of accessing the private repo.
## What happened instead

I get the following error:
Step 0 : FROM java:8
Pulling repository java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.166s
[INFO] Finished at: Sat Aug 06 11:17:17 UTC 2016
[INFO] Final Memory: 34M/595M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project server: Exception caught: Authentication is required. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project server: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)

[Describe the actual results]

The error received says "authentication is required".
two solutions:
if I remove <serverId> from the pom file, i don't get the error above - however i can't push the image to my private repo.

if i pull java:8 manually beforehand, i can add <serverId> to the pom file and i don't receive the error above.
## Software:
- docker version: [Add docker version here, client and server]
  client:1.6.2
  server:1.6.2
- docker-maven-plugin version: [Add docker-maven-plugin version here]
  0.4.11
- maven version: [Add maven version here]
  maven:3.0.5
## Full backtrace

``` text
[Paste full backtrace here]
```

**Comment by s17t** [comment] 2016-12-12 08:38
This is a duplicate of later #140

**Comment by davidxia** [comment] 2018-05-22 02:39
I am not sure if this is still an issue, since the reports are pretty old, but #339 fixes all of the root causes.

**Closed by davidxia** 2018-05-22 02:39 UTC
