### ISSUE TITLE
Issue while building docker image

### ISSUE THREAD

**Issue by san213** [spotify/docker-maven-plugin#72] opened 2015-04-14 10:14 UTC
I am stuck at the below error while trying to build the docker image. I was using 0.1.1 maven plugin, but even after 0.2.6 there has been no help. Can anyone please tell how to solve this?

Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:968)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:795)
        at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:756)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:189)
        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
        at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:171)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by davidxia** [comment] 2015-04-14 17:42
closing bc duplicate of https://github.com/spotify/docker-maven-plugin/issues/73

**Closed by davidxia** 2015-04-14 17:42 UTC

**Comment by san213** [comment] 2015-04-14 18:11
Hi,

There is no duplicate issue page. Can you please point to the right uri?


Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.7&pv=5.0.2]

On Tue, Apr 14, 2015 at 11:12 PM, David Xia < notifications@github.com [notifications@github.com] > wrote:
Closed #72 [https://github.com/spotify/docker-maven-plugin/issues/72] .

—
Reply to this email directly or view it on GitHub
[https://github.com/spotify/docker-maven-plugin/issues/72#event-281215445] .[https://github.com/notifications/beacon/AIS4l8JT32S_lVv0874uemUF3KFLlGWjks5n_UjrgaJpZM4EAHRz.gif]

**Comment by davidxia** [comment] 2015-04-14 19:28
oops, sorry. I've updated the link
