### ISSUE TITLE
403 When getting the base image from a private registry

### ISSUE THREAD

**Issue by anovarini** [spotify/docker-maven-plugin#69] opened 2015-04-13 15:36 UTC
Hello,

I managed to push my image to my private registry, setting the configuration in the settings.xml file as per instructions.
Everything works fine if the base image is already pulled using docker pull, but I get a 403 when the base image has to be pulled from scratch.

What I don't get is why the credentials work when I push but not when I pull.
Is there something I'm missing in my reasoning? Are there two different settings for that (I hope not)?

Thanks,
Alessandro

**Comment by paskos** [comment] 2015-05-01 18:25
+1

**Comment by dmasse76** [comment] 2015-05-01 18:28
I have the same behaviour.  I have a base image located in a private registry with settings.xml correctly configured but the plugin cannot download the image from the private registry.  I have to manually pull the image prior to build.
+1

**Comment by kevtaylor** [comment] 2015-05-05 10:27
The problem is actually in the docker-client, called by the plugin. I raised the issue here:
https://github.com/spotify/docker-client/issues/157

**Comment by kevtaylor** [comment] 2015-06-16 08:14
This is now resolved by PR https://github.com/spotify/docker-client/pull/171

**Comment by davidxia** [comment] 2015-08-03 04:50
Closing as I think this is resolved according to @kevtaylor.

**Closed by davidxia** 2015-08-03 04:50 UTC
