### ISSUE TITLE
Better feedback on error

### ISSUE THREAD

**Issue by ggtools** [spotify/docker-maven-plugin#119] opened 2015-08-03 10:21 UTC
I recently had an issue creating an image using the `docker-maven-plugin`. It was simply that the `Dockerfile` was not copied to the working directory but it only happened on the CI server. My problem here is that the feedback I got from Maven was not really useful at all:

```
[INFO] Building image evollis/middle-business:049daf7
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[CUT]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.905 s
[INFO] Finished at: 2015-07-31T17:13:45+00:00
[INFO] Final Memory: 91M/1164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.12:build (docker-image-create) on project xxx: Exception caught: Request error: POST unix://localhost:80/build?t=evollis/middle-business:049daf7: 500: HTTP 500 Internal Server Error -> [Help 1]
```

I don't know if it is possible to get more feedback from the docker daemon but that'll have been great to get the underlying error message

**Comment by tatsuyaoiw** [comment] 2015-09-16 05:43
+1

**Comment by ghiron** [comment] 2015-10-14 10:55
+1

**Comment by MarkNBroadhead** [comment] 2016-07-11 14:35
+1 Having an issue right now and troubleshooting is difficult without more visibility.

**Comment by fc572** [comment] 2017-02-01 15:40
I have had the same issue. This happens because Docker build process doesn't like upper case letters in the image name.
Change the artifact id in your pom file to have all lowercase letters.

**Comment by davidxia** [comment] 2018-05-27 23:55
This looks like a duplicate of [this issue](https://github.com/spotify/docker-maven-plugin/issues/206). Closing this one.

**Closed by davidxia** 2018-05-27 23:55 UTC
