### ISSUE TITLE
user docker login credentials file for push images

### ISSUE THREAD

**Issue by herau** [spotify/docker-maven-plugin#143] opened 2015-10-07 19:47 UTC
Currently, we have to declare docker credentials in the maven `settings.xml` file. 
It will be nice that the maven plugin use the docker login credentials for push images, generated by the docker command:

``` bash
docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
```

**Comment by efontana** [comment] 2015-10-30 18:25
It picks up mine from settings.xml ? so long as the server id matches and there is an <email> tag under configuration

**Comment by mattnworb** [comment] 2015-11-06 18:45
should be feasible once https://github.com/spotify/docker-client/pull/254 and/or https://github.com/spotify/docker-client/pull/266 are complete.

**Comment by walbus** [comment] 2015-11-19 15:07
Try adding:
<dependencies>
  <dependency>
    <groupId>com.spotify</groupId>
    <artifactId>docker-client</artifactId>
    <version>3.3.1</version>
  </dependency>
</dependencies>
To the plugin.
This will force it to use a newer version of the docker-client.

**Comment by jgeorgeson** [comment] 2016-01-14 23:28
As best I can tell all the prerequisite issues from docker-client have been resolved, but the build goal fails for me with the suggessted overridden dependency

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.10:build (docker-build) on project hello: Execution docker-build of goal com.spotify:docker-maven-plugin:0.3.10:build failed: An API incompatibility was encountered while executing com.spotify:docker-maven-plugin:0.3.10:build: java.lang.VerifyError: class com.fasterxml.jackson.datatype.guava.deser.HostAndPortDeserializer overrides final method deserialize.(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/lang/Object;
[...]
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

Being able to using the ~/docker/config.json is of importance in our organization because we have multiple private registries that all require authentication and need to push and pull from different registries. For example we have approved base images in one registry and push the images of our applications which build upon those base images to a different registry.

I tried working with the the settings.xml method of storing encrypted password, but I don't see any logical way to handle authenticating to multiple registries this way, and I can't seem to get it to work just for the registry we pull base images from.

Unrelated .. what's with the 250+ release builds going out in the last 24 hrs?

**Comment by mattnworb** [comment] 2016-01-15 15:15
@jgeorgeson the jenkins instance we use to do release builds went a little haywire overnight.

I'll take a look at upgrading docker-client officially within the plugin.

**Comment by jgeorgeson** [comment] 2016-01-20 19:26
I finally have the serverId configuration to work to download my base image from a private/authenticated registry during the build. So now I'm trying to build 0.4.0-SNAPSHOT from source now that you've merged the docker-client upgrade to use the ~/.docker/config.json credentials instead of the serverId, so that I can push to a different private/authenticated registry then where my base image was pulled from. I changed all the src/it/**/pom.xml to use my private dockerhub caching registry (Artifactory) for the baseImage and ran `docker login server:port` to store the credentials in ~/.docker/config.json. Running `mvn clean install` is failing on all those IT projects.

```
Failed to execute goal com.spotify:docker-maven-plugin:0.4.0-SNAPSHOT:build (default-build) on project with-many-modules-a: Exception caught: Authentication is required.
```

I've confirmed that a manual `docker pull server:port/java` pulls the image. I've tried on both RHEL 6 + Docker 1.7.1 and RHEL7 with Docker 1.9.1.

**Comment by jgeorgeson** [comment] 2016-02-03 17:12
Pretty much abandoned RHEL6 + Docker 1.7.1 at this point, none of our development teams seem to need that build platform.

Using the released 0.4.0, I'm still receiving the authentication required failure if I don't use both the _serverId_ and _repositoryUrl_ property with credentials in settings.xml. I tried using just the _repositoryUrl_ property but same failure.

**Comment by leitzler** [comment] 2016-03-01 14:15
@jgeorgeson Did you manage to get any further? Have the same issue..

**Comment by jgeorgeson** [comment] 2016-03-04 02:14
@leitzler No, I haven't got this to work yet.

**Comment by jgeorgeson** [comment] 2016-05-16 19:43
It seems to be working in the 0.4.9 release with the new [configuration parameter](https://github.com/jgeorgeson/docker-maven-plugin#using-docker-config-file-for-authentication)

**Closed** 2017-06-07 01:15 UTC
