### ISSUE TITLE
Pushing even when unit tests fail

### ISSUE THREAD

**Issue by nissane** [spotify/docker-maven-plugin#182] opened 2016-01-31 22:38 UTC
Is there a way to get this not to build/push the docker containers if there are test failures?

Thanks.

**Comment by mattnworb** [comment] 2016-01-31 23:36
More details about how you are using the plugin are needed to provide any sort of answer to this. Typically Maven stops the build at the "test" phase if tests fail, so a conventional setup where you bind this plugin to package phase and *don't* tell Maven not to ignore test failures shouldn't exhibit the behavior you are talking about. But again without seeing a pom there is nothing to do but speculate.

**Comment by nissane** [comment] 2016-02-01 01:07
Hey Thanks for the response.  I am building on Jenkins.  using mvn clean install -Pdocker
pom file is below (I modified it slightly to make it more readable)

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.myproject</groupId>
		<artifactId>myproject-core</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>server</artifactId>
	<packaging>war</packaging>

	<prerequisites>
		<maven>${mavenVersion}</maven>
	</prerequisites>

	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
			</plugin>

		</plugins>
	</build>

	<profiles>
		<profile>
			<id>docker</id>
			<activation>
				<property>
					<name>docker</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>com.spotify</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>build</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<imageName>myproject/jetty:1.0</imageName>
							
							<dockerDirectory>docker</dockerDirectory>
							<resources>
								<resource>
									<targetPath>/jetty/webapps</targetPath>
									<directory>${project.build.directory}</directory>
									<include>${project.build.finalName}.war</include>
								</resource>
							</resources>
						</configuration>
					</plugin>

				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by mattnworb** [comment] 2016-02-01 13:27
What's in your parent Pom? Are you configuring maven-surefire-plugin anywhere? Does the sonar plugin do a forked build?

Can you create a simplified project/pom that reproduces your issue?

**Comment by mattnworb** [comment] 2016-09-19 13:51
closing due to a lack of updates - but please re-open if you have a way to reproduce this issue.

**Closed by mattnworb** 2016-09-19 13:51 UTC
