### ISSUE TITLE
Authentication support with AWS ECR

### ISSUE THREAD

**Issue by eoliphan** [spotify/docker-maven-plugin#181] opened 2016-01-29 21:24 UTC
Hi, we're using Amazon's ECR as a docker repository.  As opposed to the usual username/password approach, it depends on issuing a 'docker login' that is generated from an AWS client command.  And the login is valid for a certain period of time.  such that 'docker push/pull/etc' commands are valid until the login expires.  The plugin appears to expect traditional login/passwords for private repos so it doesn't work right now.

**Comment by ernestm** [comment] 2016-02-11 19:21
+1

**Comment by bobjana** [comment] 2016-02-15 09:22
+1

**Comment by mattnworb** [comment] 2016-02-16 15:14
We don't use AWS ECR ourselves but we would be more than happy to review and merge any PRs adding this functionality. With that said though, it would seem challenging to support this from within Maven, at least if you expect the build to be non-interactive.

**Comment by pramodsetlur** [comment] 2016-04-13 03:04
+1

**Comment by rbedemann** [comment] 2016-04-23 15:09
+1

**Comment by rbedemann** [comment] 2016-04-24 09:01
i've been sending a pull request for supporting the usage of ~/.docker/config.json files. with that, it is now possible to push images to AWS ECR if you logged in with the specific command right before (this can also be done in jenkins, if you execute your login command as pre-build step)

hopefully they merge the changes into their branch... for me it's perfectly working now!

**Comment by colin-icontrol** [comment] 2016-04-26 14:26
I was very happy to see this pull request get added to the release. However I seem to be having problems getting a publication to work.

I have the following configuration in my module:

`            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.6</version>
                <configuration>
                    <imageName>${docker.image.prefix}/${project.artifactId}:${project.version}</imageName>
                    <dockerDirectory>${project.basedir}/src/main/docker</dockerDirectory>
                    <useConfigFile>true</useConfigFile>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>tag-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>tag</goal>
                        </goals>
                        <configuration>
                            <forceTags>true</forceTags>
                            <image>${docker.image.prefix}/${project.artifactId}:${project.version}</image>
                            <newName>${docker.registry.host}/${docker.image.prefix}/${project.artifactId}:${project.version}</newName>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-image</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <useConfigFile>true</useConfigFile>
                            <forceTags>true</forceTags>
                            <imageName>${docker.registry.host}/${docker.image.prefix}/${project.artifactId}:${project.version}</imageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`

After executing an AWS docker login and a  'mvn clean deploy -X' I see 5 retries and the following error:

`[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.6:push (push-image) on project discovery: Exception caught: push or pull <myaccount>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>/<myimage> is already in progress -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.6:push (push-image) on project discovery: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:126)
	at com.spotify.docker.PushMojo.execute(PushMojo.java:38)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.spotify.docker.client.exceptions.DockerException: push or pull <myaccount>.dkr.ecr.us-east-1.amazonaws.com/<myrepo>/<myimage> is already in progress
	at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:52)
	at com.spotify.docker.Utils$DigestExtractingProgressHandler.progress(Utils.java:149)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1015)
	at com.spotify.docker.Utils.pushImage(Utils.java:83)
	at com.spotify.docker.PushMojo.execute(PushMojo.java:47)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:124)
	... 22 more
[ERROR] 
`

Any ideas on what is causing this? A 'docker push' from the command line works fine in this case, even if executing right after the failed maven command.

**Comment by rbedemann** [comment] 2016-04-26 14:31
As the exception says, it seems as two push processes run in parallel. Have you already evaluated that?

**Comment by rbedemann** [comment] 2016-04-26 14:34
By the way: which version are you using? As far as I know, the changes will be available in 0.4.8

**Comment by colin-icontrol** [comment] 2016-04-26 14:37
0.4.6. It didn't complain about the configuration, and the docs were updated, so I was under the impression that that was the correct version. When is 0.4.8 due?

The docker push already running may be due to an earlier cancelled docker push. It appears to be a docker mac thing. I'm pursuing that avenue as well.

**Comment by rbedemann** [comment] 2016-04-26 15:14
I think the plugin ignores config tags, that it does not know... 

Maybe @mattnworb can tell something about release plans.

**Comment by colin-icontrol** [comment] 2016-04-28 21:11
@mattnworb , any timeframe for the release that includes publishing to AWS ECR?

**Comment by davidxia** [comment] 2016-04-29 14:37
0.4.9 has been released with the patch in #224.

**Closed by davidxia** 2016-04-29 14:37 UTC
Labels: enhancement, help wanted

**Comment by petrucristescu** [comment] 2017-06-21 07:46
+1
